// Dados compactos de todas as 295 cidades de SC + 27 capitais do Brasil
// Formato: [nome, slug, regiao, porte, economia, comarca]
// porte: 'pequena' (<50k), 'media' (50-200k), 'grande' (>200k)
// regiao: região geográfica de SC ou 'CAPITAL' para capitais

export const regioesSC = {
  'Grande Florianópolis': { desc: 'região metropolitana de Florianópolis', popMessage: 'grande centro urbano', economiaPadrao: 'Comércio, Serviços, Turismo e Construção Civil' },
  'Sul Catarinense': { desc: 'região sul do estado', popMessage: 'polo regional', economiaPadrao: 'Indústria, Comércio, Agricultura e Serviços' },
  'Norte Catarinense': { desc: 'região norte do estado', popMessage: 'polo industrial', economiaPadrao: 'Indústria, Comércio, Tecnologia e Serviços' },
  'Vale do Itajaí': { desc: 'região do Vale do Itajaí', popMessage: 'polo econômico', economiaPadrao: 'Indústria Têxtil, Comércio, Tecnologia e Serviços' },
  'Oeste Catarinense': { desc: 'região oeste do estado', popMessage: 'polo agroindustrial', economiaPadrao: 'Agroindústria, Comércio, Agricultura e Serviços' },
  'Serra Catarinense': { desc: 'região serrana do estado', popMessage: 'destino turístico', economiaPadrao: 'Turismo, Agricultura, Comércio e Serviços' },
  'Meio-Oeste': { desc: 'região meio-oeste catarinense', popMessage: 'centro regional', economiaPadrao: 'Comércio, Agricultura, Indústria e Serviços' },
  'Planalto Norte': { desc: 'região do planalto norte', popMessage: 'polo regional', economiaPadrao: 'Agricultura, Comércio, Indústria e Serviços' },
}

export const capitaisData = [
  ['Rio Branco', 'rio-branco', 'AC', 'Norte', 'Acre', 'Zona da Mata Norte'],
  ['Maceió', 'maceio', 'AL', 'Nordeste', 'Alagoas', 'Litorânea'],
  ['Macapá', 'macapa', 'AP', 'Norte', 'Amapá', 'Amazônica'],
  ['Manaus', 'manaus', 'AM', 'Norte', 'Amazonas', 'Amazônica'],
  ['Salvador', 'salvador', 'BA', 'Nordeste', 'Bahia', 'Litorânea'],
  ['Fortaleza', 'fortaleza', 'CE', 'Nordeste', 'Ceará', 'Litorânea'],
  ['Brasília', 'brasilia', 'DF', 'Centro-Oeste', 'Distrito Federal', 'Planalto Central'],
  ['Vitória', 'vitoria', 'ES', 'Sudeste', 'Espírito Santo', 'Litorânea'],
  ['Goiânia', 'goiania', 'GO', 'Centro-Oeste', 'Goiás', 'Planalto Central'],
  ['São Luís', 'sao-luis', 'MA', 'Nordeste', 'Maranhão', 'Litorânea'],
  ['Cuiabá', 'cuiaba', 'MT', 'Centro-Oeste', 'Mato Grosso', 'Planalto Central'],
  ['Campo Grande', 'campo-grande', 'MS', 'Centro-Oeste', 'Mato Grosso do Sul', 'Planalto Central'],
  ['Belo Horizonte', 'belo-horizonte', 'MG', 'Sudeste', 'Minas Gerais', 'Região Metropolitana'],
  ['Belém', 'belem', 'PA', 'Norte', 'Pará', 'Amazônica'],
  ['João Pessoa', 'joao-pessoa', 'PB', 'Nordeste', 'Paraíba', 'Litorânea'],
  ['Curitiba', 'curitiba', 'PR', 'Sul', 'Paraná', 'Região Metropolitana'],
  ['Recife', 'recife', 'PE', 'Nordeste', 'Pernambuco', 'Litorânea'],
  ['Teresina', 'teresina', 'PI', 'Nordeste', 'Piauí', 'Planalto Central'],
  ['Rio de Janeiro', 'rio-de-janeiro', 'RJ', 'Sudeste', 'Rio de Janeiro', 'Litorânea'],
  ['Natal', 'natal', 'RN', 'Nordeste', 'Rio Grande do Norte', 'Litorânea'],
  ['Porto Alegre', 'porto-alegre', 'RS', 'Sul', 'Rio Grande do Sul', 'Região Metropolitana'],
  ['Porto Velho', 'porto-velho', 'RO', 'Norte', 'Rondônia', 'Amazônica'],
  ['Boa Vista', 'boa-vista', 'RR', 'Norte', 'Roraima', 'Amazônica'],
  ['São Paulo', 'sao-paulo', 'SP', 'Sudeste', 'São Paulo', 'Região Metropolitana'],
  ['Aracaju', 'aracaju', 'SE', 'Nordeste', 'Sergipe', 'Litorânea'],
  ['Palmas', 'palmas', 'TO', 'Norte', 'Tocantins', 'Planalto Central'],
]

// Todas as 295 cidades de SC organizadas por região
export const cidadesSC = {
  'Grande Florianópolis': [
    'Águas Mornas', 'Antônio Carlos', 'Biguaçu', 'Florianópolis', 'Governador Celso Ramos',
    'Palhoça', 'Santo Amaro da Imperatriz', 'São Bonifácio', 'São José', 'São Pedro de Alcântara',
  ],
  'Sul Catarinense': [
    'Araranguá', 'Balneário Arroio do Silva', 'Balneário Gaivota', 'Balneário Rincão', 'Criciúma',
    'Ermo', 'Forquilhinha', 'Içara', 'Jacinto Machado', 'Maracajá', 'Meleiro', 'Morro Grande',
    'Nova Veneza', 'Passo de Torres', 'Praia Grande', 'Santa Rosa do Sul', 'São João do Sul',
    'Sombrio', 'Timbé do Sul', 'Turvo', 'Garopaba', 'Imbituba', 'Laguna', 'Paulo Lopes',
    'Braço do Norte', 'Capivari de Baixo', 'Grão Pará', 'Lauro Müller', 'Pedras Grandes',
    'Rio Fortuna', 'São Ludgero', 'Tubarão', 'Armazém', 'Imaruí', 'Pescaria Brava', 'São Martinho',
    'Sangão', 'Treze de Maio',
  ],
  'Norte Catarinense': [
    'Araquari', 'Balneário Barra do Sul', 'Corupá', 'Garuva', 'Guaramirim', 'Itaiópolis',
    'Itapoá', 'Jaraguá do Sul', 'Joinville', 'Mafra', 'Massaranduba', 'Monte Castelo',
    'Papanduva', 'Rio Negrinho', 'São Bento do Sul', 'São Francisco do Sul', 'Schroeder',
    'Campo Alegre', 'Canoinhas', 'Irineópolis', 'Major Vieira', 'Porto União', 'Três Barras',
    'Bela Vista do Toldo',
  ],
  'Vale do Itajaí': [
    'Apiúna', 'Ascurra', 'Benedito Novo', 'Blumenau', 'Brusque', 'Doutor Pedrinho', 'Gaspar',
    'Guabiruba', 'Indaial', 'Luiz Alves', 'Pomerode', 'Rio dos Cedros', 'Rodeio', 'Timbó',
    'Balneário Camboriú', 'Balneário Piçarras', 'Barra Velha', 'Bombinhas', 'Camboriú',
    'Ilhota', 'Itajaí', 'Itapema', 'Navegantes', 'Penha', 'Porto Belo',
    'Agrolândia', 'Agronômica', 'Atalanta', 'Aurora', 'Braço do Trombudo', 'Chapadão do Lageado',
    'Dona Emma', 'Ibirama', 'Imbuia', 'Ituporanga', 'José Boiteux', 'Laurentino', 'Lontras',
    'Mirim Doce', 'Petrolândia', 'Pouso Redondo', 'Presidente Getúlio', 'Presidente Nereu',
    'Rio do Campo', 'Rio do Oeste', 'Rio do Sul', 'Rio do Sul', 'Salete', 'Taió', 'Trombudo Central',
    'Vidal Ramos', 'Vitor Meireles', 'Witmarsum',
  ],
  'Oeste Catarinense': [
    'Abelardo Luz', 'Água Doce', 'Águas de Chapecó', 'Águas Frias', 'Alto Bela Vista', 'Anchieta',
    'Arabutã', 'Arroio Trinta', 'Arvoredo', 'Bandeirante', 'Barra Bonita', 'Belmonte',
    'Bom Jesus do Oeste', 'Caibi', 'Calmon', 'Campo Erê', 'Caxambu do Sul', 'Chapecó',
    'Cordilheira Alta', 'Coronel Freitas', 'Coronel Martins', 'Cunha Porã', 'Cunhataí',
    'Descanso', 'Dionísio Cerqueira', 'Entre Rios', 'Faxinal dos Guedes', 'Flor do Sertão',
    'Formosa do Sul', 'Galvão', 'Guaraciaba', 'Guarujá do Sul', 'Guatambú', 'Herval d\'Oeste',
    'Ibiam', 'Ibicaré', 'Iomerê', 'Ipira', 'Iporã do Oeste', 'Ipuaçu', 'Ipumirim', 'Iraceminha',
    'Irani', 'Irati', 'Itá', 'Jaborá', 'Jardinópolis', 'Joaçaba', 'Lacerdópolis', 'Lajeado Grande',
    'Luzerna', 'Marema', 'Modelo', 'Mondaí', 'Nova Erechim', 'Nova Itaberaba', 'Novo Horizonte',
    'Ouro', 'Ouro Verde', 'Paial', 'Palma Sola', 'Palmitos', 'Passos Maia', 'Peritiba',
    'Pinhalzinho', 'Planalto Alegre', 'Ponte Serrada', 'Princesa', 'Quilombo', 'Riqueza',
    'Romelândia', 'Santa Helena', 'Santa Terezinha do Progresso', 'Santiago do Sul', 'São Bernardino',
    'São Carlos', 'São Domingos', 'São João do Oeste', 'São José do Cedro', 'São Lourenço do Oeste',
    'São Miguel da Boa Vista', 'São Miguel do Oeste', 'Saudades', 'Seara', 'Serra Alta',
    'Sul Brasil', 'Tigrinhos', 'Treze Tílias', 'Tunápolis', 'Vargeão', 'Vargem Bonita',
    'Xanxerê', 'Xavantina', 'Xaxim', 'Zortéa',
  ],
  'Serra Catarinense': [
    'Anita Garibaldi', 'Bocaina do Sul', 'Bom Jardim da Serra', 'Bom Retiro', 'Campo Belo do Sul',
    'Capão Alto', 'Celso Ramos', 'Cerro Negro', 'Correia Pinto', 'Lages', 'Otacílio Costa',
    'Painel', 'Palmeira', 'Rio Rufino', 'São Joaquim', 'São José do Cerrito', 'Urubici', 'Urupema',
    'Vaccum', 'Curitibanos', 'Frei Rogério', 'Monte Carlo', 'Ponte Alta', 'Ponte Alta do Norte',
    'Santa Cecília', 'São Cristóvão do Sul', 'Lebon Régis', 'Timbó Grande',
  ],
  'Meio-Oeste': [
    'Campos Novos', 'Catanduvas', 'Erval Velho', 'Fraiburgo', 'Herval d\'Oeste', 'Ibicaré',
    'Joaçaba', 'Lacerdópolis', 'Luzerna', 'Ouro', 'Pinheiro Preto', 'Tangará', 'Treze Tílias',
    'Videira', 'Água Doce', 'Arroio Trinta', 'Caçador', 'Calmon', 'Lebon Régis', 'Macieira',
    'Matos Costa', 'Rio das Antas', 'Timbó Grande',
  ],
  'Planalto Norte': [
    'Canoinhas', 'Irineópolis', 'Itaiópolis', 'Mafra', 'Major Vieira', 'Monte Castelo',
    'Papanduva', 'Porto União', 'Três Barras', 'Bela Vista do Toldo',
  ],
}

// Portes populacionais aproximados para usar nos templates
export const porteInfo = {
  pequena: { pop: 'até 50 mil habitantes', tipo: 'acolhedora cidade do interior', faixa: 'pequeno porte' },
  media: { pop: 'entre 50 e 200 mil habitantes', tipo: 'polo regional em crescimento', faixa: 'médio porte' },
  grande: { pop: 'mais de 200 mil habitantes', tipo: 'importante centro urbano', faixa: 'grande porte' },
}

// Mapa de cidades conhecidas com porte e economia personalizada
export const cidadesConhecidas = {
  'Joinville': { porte: 'grande', economia: 'Indústria, Tecnologia, Comércio e Serviços', comarca: 'Joinville é a maior cidade de Santa Catarina' },
  'Florianópolis': { porte: 'grande', economia: 'Turismo, Tecnologia, Comércio e Serviços', comarca: 'Capital do estado — maior comarca de SC' },
  'Blumenau': { porte: 'grande', economia: 'Indústria Têxtil, Tecnologia, Turismo e Comércio', comarca: 'Polo industrial do Vale do Itajaí' },
  'São José': { porte: 'grande', economia: 'Comércio, Serviços, Tecnologia e Construção Civil', comarca: 'Segunda maior cidade da Grande Florianópolis' },
  'Criciúma': { porte: 'grande', economia: 'Indústria, Comércio, Tecnologia e Serviços', comarca: 'Principal polo do Sul Catarinense' },
  'Chapecó': { porte: 'grande', economia: 'Agroindústria, Comércio, Tecnologia e Serviços', comarca: 'Capital do Oeste Catarinense' },
  'Itajaí': { porte: 'grande', economia: 'Portuária, Comércio, Tecnologia e Serviços', comarca: 'Maior porto de Santa Catarina' },
  'Lages': { porte: 'media', economia: 'Turismo, Agricultura, Comércio e Serviços', comarca: 'Principal cidade da Serra Catarinense' },
  'Jaraguá do Sul': { porte: 'grande', economia: 'Indústria, Tecnologia, Comércio e Serviços', comarca: 'Polo industrial do Norte Catarinense' },
  'Balneário Camboriú': { porte: 'grande', economia: 'Turismo, Construção Civil, Comércio e Serviços', comarca: 'Principal destino turístico de SC' },
  'Palhoça': { porte: 'media', economia: 'Comércio, Serviços, Construção Civil', comarca: 'Sede do escritório Will & Pereira Advocacia' },
  'Tubarão': { porte: 'media', economia: 'Indústria, Comércio, Agricultura e Serviços', comarca: 'Polo do Sul Catarinense' },
  'Brusque': { porte: 'media', economia: 'Indústria Têxtil, Comércio e Serviços', comarca: 'Importante polo têxtil de SC' },
  'Caçador': { porte: 'media', economia: 'Indústria, Comércio, Agricultura e Serviços', comarca: 'Polo do Meio-Oeste catarinense' },
  'Concórdia': { porte: 'media', economia: 'Agroindústria, Comércio e Serviços', comarca: 'Capital nacional da agroindústria' },
  'Rio do Sul': { porte: 'media', economia: 'Comércio, Indústria, Tecnologia e Serviços', comarca: 'Capital do Alto Vale do Itajaí' },
  'Mafra': { porte: 'media', economia: 'Indústria, Comércio, Agricultura e Serviços', comarca: 'Principal cidade do Planalto Norte' },
  'São Bento do Sul': { porte: 'media', economia: 'Indústria Moveleira, Comércio e Serviços', comarca: 'Polo moveleiro de SC' },
  'Indaial': { porte: 'media', economia: 'Indústria Têxtil, Tecnologia, Comércio e Serviços', comarca: 'Cidade do Vale do Itajaí' },
  'Videira': { porte: 'media', economia: 'Agroindústria, Comércio, Agricultura e Serviços', comarca: 'Capital do vinho catarinense' },
  'Canoinhas': { porte: 'media', economia: 'Indústria, Comércio, Agricultura e Serviços', comarca: 'Polo do Planalto Norte' },
  'São Miguel do Oeste': { porte: 'media', economia: 'Agroindústria, Comércio e Serviços', comarca: 'Polo do Extremo-Oeste' },
  'Araranguá': { porte: 'media', economia: 'Comércio, Indústria, Agricultura e Serviços', comarca: 'Polo do Extremo-Sul Catarinense' },
  'Timbó': { porte: 'pequena', economia: 'Indústria, Tecnologia, Comércio e Serviços', comarca: 'Cidade polo do Médio Vale do Itajaí' },
  'Laguna': { porte: 'media', economia: 'Turismo, Comércio, Pesca e Serviços', comarca: 'Cidade histórica do litoral catarinense' },
  'Imbituba': { porte: 'pequena', economia: 'Portuária, Turismo, Comércio e Serviços', comarca: 'Importante polo portuário de SC' },
  'Curitibanos': { porte: 'media', economia: 'Agricultura, Comércio, Indústria e Serviços', comarca: 'Polo da Serra Catarinense' },
  'Campos Novos': { porte: 'pequena', economia: 'Agricultura, Comércio, Indústria e Serviços', comarca: 'Capital nacional do milho' },
  'Navegantes': { porte: 'media', economia: 'Portuária, Turismo, Comércio e Serviços', comarca: 'Importante cidade portuária' },
  'Itapema': { porte: 'pequena', economia: 'Turismo, Construção Civil, Comércio e Serviços', comarca: 'Destino turístico do litoral norte' },
  'Porto Belo': { porte: 'pequena', economia: 'Turismo, Comércio, Pesca e Serviços', comarca: 'Destino turístico do litoral norte' },
  'Biguaçu': { porte: 'media', economia: 'Comércio, Indústria, Serviços e Construção Civil', comarca: 'Cidade da Grande Florianópolis' },
  'Garopaba': { porte: 'pequena', economia: 'Turismo, Pesca, Comércio e Serviços', comarca: 'Destino turístico do litoral sul' },
  'Sombrio': { porte: 'pequena', economia: 'Comércio, Agricultura, Indústria e Serviços', comarca: 'Cidade do Extremo-Sul Catarinense' },
  'Içara': { porte: 'pequena', economia: 'Indústria, Comércio, Agricultura e Serviços', comarca: 'Cidade da Região Carbonífera' },
}
